export const hateWordsList = [
    "gentuza",
    "tu puta madre",
    "pudrete",
    "que se pudran",
    "hija de puta",
    "hijadeputa",
    "hijas de puta",
    "hijasdeputa",
    "hija puta",
    "hijaputa",
    "hija de la gran puta",
    "hija de la grandísima puta",
    "hijas de la gran puta",
    "hijas de la grandísima puta",
    "hijo de puta",
    "hijodeputa",
    "hijos de puta",
    "hijosdeputa",
    "hijoputa",
    "hijo de la gran puta",
    "hijo de la grandísima puta",
    "hijos de la gran puta",
    "hijos de la grandísima puta",
    "asco de gente",
    "ascazo de gente",
    "dais asco",
    "das asco",
    "qué asco das",
    "qué asco dais",
    "qué asco dan",
    "imbécil",
    "gilipollas",
    "malnacido",
    "mal nacido",
    "mal nacida",
    "malnacida",
    "bastardo",
    "bastarda",
    "miserable",
    "vomitivo",
    "vomitiva",
    "nauseabundo",
    "nauseabunda",
    "calaña",
    "tipejo",
    "tipeja",
    "a tomar por culo",
    "vete a la mierda",
    "hdlgp",
    "parásito",
    "cómplice",
    "repugnante",
    "mamarracho",
    "mamarracha",
    "sinverguenza",
    "subnormal",
    "bocachancla",
    "piojoso",
    "piojosa",
    "mononeuronal",
    "hasta los cojones",
    "macarra",
    "inútil",
    "impresentable",
    "ruin",
    "escoria",
    "anormal",
    "merluzo",
    "zopenco",
    "descerebrado",
    "retrasado",
    "sabandija",
    "lerdo",
    "lerda",
    "mongolo",
    "mongola",
    "monguer",
    "cretino",
    "cretina",
    "ojalá te mueras",
    "ojalá sufras",
    "muérete",
    "separrata",
    "izmierda",
    "baboso",
    "mezquino",
    "mezquina",
    "que te calles",
    "callate",
    "sanguijuela",
    "paleto",
    "jilipollas",
    "lazi",
    "catalufo",
    "mermao",
    "analfabeto",
    "analfabeta",
    "lameculos",
    "comepollas",
    "palurdo",
    "palurda",
    "que te den por culo",
    "que te den por el culo",
    "apestas",
    "apestáis",
    "ñordo",
    "voxmitivo",
    "perroflauta",
    "caradura",
    "psicópata",
    "infame",
    "inmundo",
    "inmunda",
    "sátrapa",
    "indecente",
    "embustero",
    "embustera",
    "matón",
    "déspota",
    "desverguenza",
    "desvergonzado",
    "desvergonzada",
    "indigente mental",
    "indigente intelectual",
    "depravado",
    "felón",
    "chusma",
    "prepotente",
    "suciolisto",
    "putrefacto",
    "a la puta cárcel",
    "despreciable",
    "ser infecto",
    "pestilente",
    "paniaguado",
    "paniaguada",
    "llorica",
    "tontísimo",
    "tontísima",
    "payaso",
    "payasa",
    "niñato",
    "niñata",
    "tolai",
    "parguela",
    "malfollada",
    "mal follada",
    "de los cojones",
    "desgraciado",
    "desgraciada",
    "inepto",
    "soplapolleces",
    "facha",
    "fascista",
    "fachas",
    "fascistas",
    "capullo",
    "capullos",
    "idiota",
    "idiotas",
    "maricón",
    "maricones",
    "tonto",
    "tonta",
    "basura",
    "cabron",
    "cateto",
    "cateta",
    "estúpido",
    "estúpida",
    "cantamañanas",
    "cenutrio",
    "mierda",
    "canalla",
    "alimaña",
    "asesino",
    "asesina",
    "golpista",
    "etarra",
    "ni puta idea",
    "me cago en",
    "indeseable",
    "asquerosa",
    "asqueroso",
    "cobarde",
    "terrorista",
    "golpe de estado",
    "traidor",
    "rastrera",
    "rastrero",
    "crápula",
    "criminal",
    " rata",
    "nazi",
    "mentiroso",
    "mentirosa",
    "farsante",
    "hipócrita",
    "cerdo",
    "cerda",
    "puerco",
    "ignorante",
    "de mierda",
    "cornudo",
    "cornuda",
    "que te follen",
    "podemita",
    "sociata",
    "golfo",
    "golfa",
    "suicida",
    "corrupto",
    "indigno",
    "delincuente",
    "peste",
    "cínico",
    "cínica",
    "execrable",
    "perverso",
    "depravada",
    "necio",
    "necia",
    "adefesio",
    "tarado",
    "tarada",
    "roñoso",
    "roñosa",
    "fantoche",
    "estafador",
    "pútrido",
    "pútrida",
    "entre rejas",
    "fulana",
    "zorra",
    "hdp",
    "cucaracha",
    "falso",
    "feminazi"
]